### ISSUE TITLE
Canary Routing

### ISSUE THREAD

**Issue by predic8** [membrane/api-gateway#1141]
Idea:

```
# Gets 10% of traffik to /foo
<api port="2000">
     <match>
         <canary rate="0.1">
     </match>
      <path>/foo></path>
     ...
</api>
```

```
# Gets 90% of traffik to /foo
<api port="2000">
      <path>/foo></path>
     ...
</api>
```

**Comment by t-burch** [comment]
The term canary routing is made up by us I am guessing, it might not be the best term because canary deployments generally are for catching errors early. This might apply to the route as well, but common terminology by amazon and others is just weighted routing. So maybe we can add a "weight" property or a weight option to the matcher
