### ISSUE TITLE
Rewrite request Host header

### ISSUE THREAD

**Issue by jRom42** [membrane/api-gateway#1402]
Hello,

A backend web service that used to work for years has stopped working because it looks like a control is now made on the Host header in the request.
The web service still works with a curl command when accessed without membrane.

This call works
```bash
curl --request POST   --url https://<**external_webservice_fqdn**>/service   \
  --header 'accept: application/json'   \
  --header 'content-type: application/x-www-form-urlencoded'     \  
  --data username=xxxxxxxxx   \
  --data password=xxxxxxxxxx
```
 
This call does not work anymore:

```bash
curl --request POST   --url https://<**membrane_fqdn**>/service   \
  --header 'accept: application/json'   \
  --header 'content-type: application/x-www-form-urlencoded'     \  
  --data username=xxxxxxxxx   \
  --data password=xxxxxxxxxx
```

How can I overwrite the Host header before the request is sent to the target ?

I have tried with <groovy> and <setHeader> but none of them seem to work.

**Comment by predic8** [comment]
@jRom42 thanks for reporting.

Can you please post this into the "Discussions" ( https://github.com/membrane/api-gateway/discussions )  section? It might be of interesst for other user. In order to help some details might be helpful:

- Membrane version
- proxies.xml configuration
- Log output of Membrane. Use <log/> element inside your api/serviceProxy to log headers
